name: bqplot-test
channels:
    - conda-forge
dependencies:
    - pip
    - python
    - yarn
    - ipywidgets >=5.2.2
    - traitlets >=4.3.0
    - traittypes >=0.0.6
    - numpy >=1.10.4
    - pandas
    - jupyter
    - jupyterlab=3
    - jupyter-packaging
    - pytest
    - pytest-cov
    - selenium
    - mock
    - nose
