name: bqplot_docs
channels:
 - conda-forge
dependencies:
 - python=3.5
 - traitlets
 - traittypes
 - widgetsnbextension
 - numpy
 - pandas
 - bqplot
 - nbsphinx
 - pip:
    - jupyter_sphinx
    - ipywidgets>=6.0.0rc2
