package:
  name: bqplot
  version: 0.5.3

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  path: ../

requirements:
  build:
    - python
    - numpy
    - setuptools
    - jupyter
    - pandas

  run:
    - python
    - numpy
    - setuptools
    - jupyter
    - pandas

test:
  imports:
    - bqplot

about:
  summary: Bloomberg plotting library for Jupyter widgets
  license_file: LICENSE
  license: Apache License 2.0
